server:
  port: 8081
  #ssl:
    #trust-store: src/main/resources/trustore.jks
    #trust-store-password: 1234

spring:
  application:
    name: mail-sender
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    sender:
      type: web
    service:
      name: mail-sender
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 25
    username: aaron.zumarraga@gmail.com
    password: ivtabubd1ybcxwzb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl: 
            trust: smtp.gmail.com
            enable: false
          socketFactory:
            fallback: true
  rabbitmq:
    host: vulture-01.rmq.cloudamqp.com
    port: 5672
    username: vumjimdj
    password: MSRyOJmr4WNo8gWRMwyTmTOqq-XqnA2Q
    virtual-host: username
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
